export const SET_RENDERING_PROFILES = 'INIT_DATA_FETCH';
export const APPEND_STUDENTS_ROLL = 'APPEND_STUDENTS_ROLL';
export const CLEAR_STUDENTS_ROLL = 'CLEAR_STUDENTS_ROLL';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';